version: '3.8'

services:
  backend:
    build: ./backend
    container_name: autotrack-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    image: nginx:alpine
    container_name: autotrack-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always
